# Generated by Django 5.0.6 on 2025-03-06 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_status_options_rename_content_status_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='statuses/'),
        ),
    ]
