# Generated by Django 5.0.6 on 2024-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
    ]
