# Generated by Django 5.0.6 on 2024-09-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_gender_search_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender_search',
            new_name='looking_for',
        ),
    ]
