# Generated by Django 5.0.6 on 2024-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_state_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/avatar.jpg', upload_to='profiles/'),
        ),
    ]
