# Generated by Django 5.0.6 on 2024-09-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='profile_pics/'),
        ),
    ]
