# Generated by Django 5.0.6 on 2024-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
