# Generated by Django 5.0.6 on 2024-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
    ]
