# Generated by Django 5.0.6 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
