# Generated by Django 5.0.6 on 2025-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_image1_user_image2_user_image3_user_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image3',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image4',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image5',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile/'),
        ),
    ]
