# Generated by Django 5.0.6 on 2025-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_image1_alter_user_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
    ]
