# Generated by Django 5.0.6 on 2025-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
