# Generated by Django 5.0.6 on 2025-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image3',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image4',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image5',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
    ]
